name: Coverage
on:
  push:

jobs:
  test:
    name: Coverage report
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.11-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.11-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run coverage
        run: |
          tox -q -e coverage >> $GITHUB_STEP_SUMMARY
